// a simple file that defines the kinematics for StompyMk1
// the 8x8 array here is generated by Gatefinder (https://github.com/brooks42/StompyMk1Gatefinder)

#ifndef __KIN__
#define __KIN__

// the values for our servos when the gait is moving forward
const int servoValuesMovingForward[8][8] = { 0/* fill in all the numbers from Gatefinder here */ };

// values for when the gait is rotating left or right
const int servoValuesRotatingLeft[8][8] = { 0/* fill in all the numbers from Gatefinder here */ };
const int servoValuesRotatingRight[8][8] = { 0/* fill in all the numbers from Gatefinder here */ };

#endif
